### ISSUE TITLE
HTTP Testing must be in testing directory no inside the framework 

### ISSUE THREAD

**Issue by wnunezc** [lightpack/framework#104]
[Testing/Http](https://github.com/lightpack/framework/tree/main/src/Framework/Testing/Http)

HTTP Testing must be in testing directory no inside the framework

**Comment by pradeep-tiwari** [comment]
@arcanisgk Yes, you are absolutely correct. 
I misplaced it by mistake. Will resolve this and close it soon. Thanx.

**Comment by wnunezc** [comment]
@pradeep-tiwari  Hello, it's good to have helped you; Would you like me to review your work, maybe I can make some contributions?

**Comment by pradeep-tiwari** [comment]
@arcanisgk Sure, that would be great. I would be thankful to have your attention on this project working towards making it production ready soon. It would be great if you **star** this repo: [Lightpack Framework](https://github.com/lightpack/lightpack)

Also please check this link: 

[Project Site](https://lightpack.github.io/)
[GitHub Profile](https://github.com/lightpack)

**Comment by wnunezc** [comment]
Any chat channel or discord???

**Comment by pradeep-tiwari** [comment]
@arcanisgk Actually [HTTP Testing](https://github.com/lightpack/framework/tree/main/src/Framework/Testing/Http) is not a test case. It is a base class that extends support for unit/feature testing in **Lightpack** framework.

Even I got confused 😅. I will close this issue now.

**Comment by wnunezc** [comment]
I still think that it is a utility for test cases and that it should not be or be part of the framework...
