### ISSUE TITLE
desired structure?

### ISSUE THREAD

**Issue by wnunezc** [lightpack/framework#114]
There is something that is not clear to me; Or maybe it's too early to ask:

This framework is oriented to what type of web structure: ???

Single-page application (SPA)
Multi-page Web Applications (MPA)
Web application per component (CPA)

I didn't find anything in the documentation that makes it easy to know in advance what to expect from the framework; If you could add some screenshots that would be great.

**Comment by pradeep-tiwari** [comment]
@arcanisgk This framework aims building web apps and APIs that you can build with frameworks like Codeigniter, Laravel, YII, Phalcon, etc. 

I know that documentation needs to be more exhaustive as well as it should have some good get started video tutorials too. This is a work in progress and I am planning out a layout for other devs who would like to contribute to this project.

**Comment by wnunezc** [comment]
@pradeep-tiwari sounds interesting the current problem you have is that I don't know where to start; As a developer it is not clear to me, for example:
1. What is the basic setup of my development environment, mandatory and recommended requirements.
2. Where and how should I configure the framework; What alternative configurations do you have?
3. Once the framework is installed and configured, where should I go or where should I start my development.

I don't like that they use other framework names to say make it equal to or is equal to... you don't know if I've touched those frameworks in my life and if I have to study another framework to develop in this one, they preferred to stay in that other one...

**Comment by pradeep-tiwari** [comment]
@arcanisgk You are right. As I said, I am planning to layout a guide for devs to work/contribute to this framework. I will notify here in the same issue when I am done.

**Comment by wnunezc** [comment]
For example, I have visited the documentation site and the first thing I see is the quick installation, which is perfect, easy and simple. On the contrary, the example tutorial is extremely long, this should go at the end as a quick guide. Now, like all developers, the first thing I do when implementing my personal setup for local development using this framework... I haven't found it as easily as I did with the express install...

Assuming this is like symphony; and that uses environment variables for its configuration I look for this... and when I enter I find this sentence:

`php lucy create:env`

who is lucy? where is lucy? how does lucy work?

if I should use a command with a pseudonym; at the beginning of the article you must put a link that refers to everything that this command does.

**Comment by pradeep-tiwari** [comment]
@arcanisgk Hmm.. completely valid point. Let me update the get started doc in a day or two.

**Comment by wnunezc** [comment]
So I'm trying to read your code, which looks good but you don't have a single line of documentation, other than the copyright; then it is a bit complicated for us to work on the methods within the code of your framework, improve, support, correct and report any changes...

I leave you an example of a library that I created to detect if you are in CLI or Web. 
https://github.com/arcanisgk/WEB-CLI-Detector

if you go directly to the class you will see how it is documented.

![image](https://user-images.githubusercontent.com/1207306/185195653-551cb7e5-05fa-409f-8716-6412d2e6c602.png)

This documentation is very very important and valued at the time you are developing.

I keep guessing what makes each method in your code very tiring XD. But I know that all that can be improved.

**Comment by wnunezc** [comment]
there is no direct way to leave messages: discord, slack, etc... you have to leave a message here and then you make 10 changes and you don't get a response until 3, 4 days later...
